http://localhost:8080/users/7

###
http://localhost:8080/users

###

DELETE http://localhost:8080/users
###

DELETE http://localhost:8080/users/42

###

POST http://localhost:8080/users 
content-type: application/json

{
    "username": "khaoula",
    "email": "elmajnikhaoula9@gmail.com",
    "password": "VFDX3456",
    "role": "admin"
}


###

PUT http://localhost:8080/users/32
content-type: application/json

{
    "username": "elmajni",
    "email": "elmajnikhaoula99@gmail.com",
    "password": "VFDX3456",
    "role": "admin"
}

### Step over the first 8 users and take 2 users 
GET http://localhost:8080/users/offset/8/limit/2



### Get all admins
GET http://localhost:8080/users/admins

### Get all authors
GET http://localhost:8080/users/authors

### Get all guests
GET http://localhost:8080/users/guests

### Get user by email
GET http://localhost:8080/users/email/Einar26@yahoo.com



###
GET http://localhost:8080/users/30
###
GET http://localhost:8080/users?usersNbr

###
GET http://localhost:8080/articles

###
GET http://localhost:8080/articles/1

###
GET http://localhost:8080/articles/7
###
POST http://localhost:8080/articles
content-type: application/json

{
    "title": "YUP",
    "content": "khaoula khaoula khaoula khaoula khaoula",
    "published": 1,
    "userid" : 10
}

###

DELETE http://localhost:8080/articles/11
###

PUT http://localhost:8080/articles/12
content-type: application/json
{
    "title": "yos",
    "content": "khaoula khaoula khaoula khaoula ok",
    "published": 0,
    "userId" : 10
}

### Step over the first 8 users and take 2 users 
GET http://localhost:8080/articles/offset/8/limit/2


### Get article by userid
GET http://localhost:8080/articles/userid/5

### Get article by title
GET http://localhost:8080/articles/title/khaoula

###
GET http://localhost:8080/articles?articlesNbr
###

DELETE http://localhost:8080/articles/11

###
http://localhost:8080/comments

###
GET http://localhost:8080/comments?commentsNbr

###
GET http://localhost:8080/comments/4

###
POST http://localhost:8080/comments
content-type: application/json

{
    "content": "khaoula khaoula khaoula khaoula khaoula",
    "ArticleId": 1
}

###

PUT http://localhost:8080/comments/11
content-type: application/json
{
    "content": "khaoula khaoula khaoula khaoula elmajni",
    "ArticleId": 13
}

###

DELETE http://localhost:8080/comments/11


###
GET http://localhost:8080/tags

###
GET http://localhost:8080/tags?tagsNbr


###
GET http://localhost:8080/tags/11

###
POST http://localhost:8080/tags
content-type: application/json

{
    "name": "mama khaoula khaoula"
}

###

PUT http://localhost:8080/tags/11
content-type: application/json

{
   "name": "ok khaoula khaoula elmajni"
}

